// <auto-generated />
using System;
using Datos.Modelos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datos.Migrations
{
    [DbContext(typeof(PizzeriaDbContext))]
    [Migration("20210208080321_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Datos.Modelos.DetallePedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("estadoDetalle")
                        .HasColumnType("int");

                    b.Property<int?>("pedidoid")
                        .HasColumnType("int");

                    b.Property<int?>("pizzaid")
                        .HasColumnType("int");

                    b.Property<float>("subTotal")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("pedidoid");

                    b.HasIndex("pizzaid");

                    b.ToTable("DetallePedido");
                });

            modelBuilder.Entity("Datos.Modelos.Factura", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("formaDePago")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("pedidoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("pedidoid");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("Datos.Modelos.Ingrediente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Ingrediente");
                });

            modelBuilder.Entity("Datos.Modelos.Pedido", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("clienteNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("demoraAprox")
                        .HasColumnType("int");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<float>("montoTotal")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("Datos.Modelos.Pizza", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("precioPorcion")
                        .HasColumnType("real");

                    b.Property<string>("variedad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Pizza");
                });

            modelBuilder.Entity("IngredientePizza", b =>
                {
                    b.Property<int>("ingredientesid")
                        .HasColumnType("int");

                    b.Property<int>("pizzasid")
                        .HasColumnType("int");

                    b.HasKey("ingredientesid", "pizzasid");

                    b.HasIndex("pizzasid");

                    b.ToTable("IngredientePizza");
                });

            modelBuilder.Entity("Datos.Modelos.DetallePedido", b =>
                {
                    b.HasOne("Datos.Modelos.Pedido", "pedido")
                        .WithMany()
                        .HasForeignKey("pedidoid");

                    b.HasOne("Datos.Modelos.Pizza", "pizza")
                        .WithMany()
                        .HasForeignKey("pizzaid");

                    b.Navigation("pedido");

                    b.Navigation("pizza");
                });

            modelBuilder.Entity("Datos.Modelos.Factura", b =>
                {
                    b.HasOne("Datos.Modelos.Pedido", "pedido")
                        .WithMany()
                        .HasForeignKey("pedidoid");

                    b.Navigation("pedido");
                });

            modelBuilder.Entity("IngredientePizza", b =>
                {
                    b.HasOne("Datos.Modelos.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("ingredientesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Datos.Modelos.Pizza", null)
                        .WithMany()
                        .HasForeignKey("pizzasid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
